th vector_fwd_validation.lua > Results/vector_fwd_threshold.txt
th vector_bwd_validation.lua > Results/vector_bwd_threshold.txt
th vector_murphy_fwd_validation.lua > Results/murphy_vector_fwd_threshold.txt
th vector_murphy_bwd_validation.lua > Results/murphy_vector_bwd_threshold.txt
th vector_cross_validation.lua > Results/vector_network_murphy.txt
th vector_cross_validation1.lua > Results/vector_murphy_network.txt
th fwd_validation.lua > Results/fwd_threshold.txt
th bwd_validation.lua > Results/bwd_threshold.txt
th murphy_fwd_validation.lua > Results/murphy_fwd_threshold.txt
th murphy_bwd_validation.lua > Results/murphy_bwd_threshold.txt
th cross_validation.lua > Results/network_murphy.txt
th cross_validation1.lua > Results/murphy_network.txt
